#########################################
## Configuration for codecov coverage####
#########################################
coverage:
  ignore:
  - app/src/main/java/nl/tudelft/cs4160/trustchain_android/main/.*
  status:
    project:
      default:
        threshold: 50%
