language: android

jdk:
    - oraclejdk8

sudo: false
dist: trusty
env:
  global:
    - ANDROID_EMU_API_LEVEL=25


android:
  components:
    - tools
    - platform-tools
    - tools
    # The BuildTools version used by the project
    - build-tools-26.0.2
    # The SDK version used to compile the project
    - android-25
    # System image that is gonna be used.
    - sys-img-$ANDROID_ABI-google_apis-$ANDROID_EMU_API_LEVEL

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Android SDK
    - $HOME/android-sdk-dl
    - $HOME/android-sdk

script:
  - ./gradlew jacocoTestReport --info

after_success:
  - bash <(curl -s https://codecov.io/bash)