language: android
android:
  components:
    #- tools
    #- platform-tools
    #- tools

    # The BuildTools version used by the project
    - build-tools-26.0.2

    # The SDK version used to compile the project
    - android-25
